use serde::{Deserialize, Serialize};
use std::str::FromStr;

/// An enum representing the different breeds of cattle.
///
/// Initial data from: <https://breeds.okstate.edu/cattle/>
///
/// # Examples
/// ``` rust
/// use livestock_rs::cattle::CattleBreed;
///
/// let breed = CattleBreed::Angus;
/// println!("{:?}", breed);
/// ```
#[derive(Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum CattleBreed {
    Africander,
    Akaushi,
    Alberes,
    Alentejana,
    Allmogekor,
    AmericanBreed,
    AmericanBraford,
    AmericanWhitePark,
    Amerifax,
    AmritMahal,
    AnatolianBlack,
    AndalusianBlack,
    AndalusianGrey,
    Angeln,
    Angus,
    Ankole,
    AnkoleWatusi,
    ArgentineCriollo,
    AsturianMountain,
    AsturianValley,
    Aubrac,
    AulieAta,
    AustralianBraford,
    AustralianFriesianSahiwal,
    AustralianLowline,
    AustralianMilkingZebu,
    Ayrshire,
    Azaouak,
    Bachaur,
    Baladi,
    BaltataRomaneasca,
    Barka,
    Barzona,
    Bazadais,
    Bearnais,
    Beefalo,
    Beefmaker,
    Beefmaster,
    BelarusRed,
    BelgianBlue,
    BelgianRed,
    BelmontAdaptaur,
    BelmontRed,
    BeltedGalloway,
    Bengali,
    Berrendas,
    Bhagnari,
    BlackHereford,
    BlacksidedTrondheimAndNorland,
    BlancaCacerena,
    BlancoOrejinegro,
    BlondeDAquitaine,
    Bonsmara,
    Boran,
    Bordelais,
    Brahman,
    Brahmousin,
    Brangus,
    Braunvieh,
    BritishWhite,
    BrownSwiss,
    Busa,
    Cachena,
    CanadianHighland,
    Canadienne,
    CanaryIsland,
    Canchim,
    CarinthianBlond,
    Caucasian,
    Channi,
    Charbray,
    Charolais,
    Chianina,
    Chinampo,
    ChineseBlackAndWhite,
    ChineseMongolian,
    ChineseXinjiangBrown,
    Cholistani,
    Corriente,
    CostenoConCuernos,
    Dajal,
    Damascus,
    Damietta,
    Dangi,
    DanishJersey,
    DanishRed,
    Deoni,
    Devon,
    Dexter,
    Dhanni,
    Djali,
    Dolafe,
    Droughtmaster,
    Dulong,
    DutchBelted,
    DutchFriesian,
    EastAnatolianRed,
    EnderbyIsland,
    EnglishLonghorn,
    EstonianRed,
    Evolene,
    Fighting,
    Finnish,
    Fjall,
    FloridaCracker,
    GalicianBlond,
    Galloway,
    Gaolao,
    Gascon,
    Gelbray,
    Gelbvieh,
    GermanAngusMoiled,
    GermanRedPied,
    Gir,
    Glan,
    Gloucester,
    Gobra,
    GreekShorthorn,
    GreekSteppe,
    Groningen,
    Guernsey,
    Guzerat,
    Hallikar,
    Hariana,
    Harton,
    HaysConverter,
    Hereford,
    Herens,
    Highland,
    Hinterwald,
    HolandoArgentino,
    Holstein,
    Horro,
    HungarianGrey,
    Icelandic,
    Illawarra,
    IndoBrazilian,
    IrishMoiled,
    IsraeliHolstein,
    IsraeliRed,
    Istoben,
    JamaicaBlack,
    JamaicaHope,
    JamaicaRed,
    Jaulan,
    JaulanSharabi,
    Jersey,
    Kangayam,
    Kankrej,
    KaranFries,
    KaranSwiss,
    Kazakh,
    Kenwariya,
    Kerry,
    Kherigarh,
    Khillari,
    Kholmogory,
    Kilis,
    KrishnaValley,
    KurdiBlack,
    Kuri,
    LatvianBrown,
    Limousin,
    Limpurger,
    LincolnRed,
    LithuanianRed,
    Lohani,
    Lourdais,
    Luing,
    MadagascarZebu,
    MaineAnjou,
    Malvi,
    Mandalong,
    Marchigiana,
    Maremmana,
    Masai,
    Mashona,
    Maure,
    Mazandarani,
    MeuseRhineYssel,
    Mewati,
    MilkingDevon,
    MilkingShorthorn,
    MiniatureZebu,
    Mirandesa,
    Modicana,
    Montbeliard,
    Morucha,
    Murboden,
    MurrayGrey,
    Muturu,
    Ndama,
    Nagori,
    Nanyang,
    Nelore,
    Nguni,
    Nimari,
    Normande,
    NorwegianRed,
    Ongole,
    OrmaBoran,
    Oropa,
    Ovambo,
    Parthenais,
    PhilippineNative,
    Piedmontese,
    Pinzgauer,
    PolishRed,
    PolledHereford,
    Ponwar,
    Qinchuan,
    Rath,
    Rathi,
    RatienGray,
    RedAngus,
    RedBrangus,
    RedFulani,
    RedPiedFriesian,
    RedPoll,
    RedPolledOstland,
    RedSindhi,
    RedSteppe,
    Reggiana,
    Retinta,
    Rojhan,
    Romagnola,
    Romosinuano,
    RussianBlackPied,
    RX3,
    Sahiwal,
    Salers,
    Salorn,
    SanMartinero,
    Sanhe,
    SantaCruz,
    SantaGertrudis,
    Sarabi,
    Senepol,
    Shetland,
    Shorthorn,
    Siboney,
    Simbrah,
    Simmental,
    Siri,
    SlovenianCika,
    SouthDevon,
    SudaneseFulani,
    Sussex,
    SwedishFriesian,
    SwedishRedPolled,
    SwedishRedAndWhite,
    Tarentaise,
    Telemark,
    TexasLonghorn,
    Texon,
    Tharparkar,
    Tswana,
    Tuli,
    TurkishGreySteppe,
    UkrainianBeef,
    UkrainianGrey,
    UkrainianWhitehead,
    Umblachery,
    UralBlackPied,
    VestlandFjord,
    VestlandRedPolled,
    Vosges,
    Wagyu,
    WelshBlack,
    WhitePark,
    Yanbian,
}

impl ToString for CattleBreed {
    /// Converts the CattleBreed enum to a human readable string.
    ///
    /// # Examples
    /// ``` rust
    /// use livestock_rs::cattle::CattleBreed;
    ///
    /// let angus = CattleBreed::Angus;
    /// println!("{}", angus.to_string());
    /// ```
    fn to_string(&self) -> String {
        match self {
            CattleBreed::AnkoleWatusi => "Ankole-Watusi".to_string(),
            CattleBreed::AulieAta => "Aulie-Ata".to_string(),
            CattleBreed::Bearnais => "Béarnais".to_string(),
            CattleBreed::BlancaCacerena => "Blanca Cacereña/White Cáceres".to_string(),
            CattleBreed::BlondeDAquitaine => "Blonde d'Aquitaine".to_string(),
            CattleBreed::ChineseBlackAndWhite => "Chinese Black-and-White".to_string(),
            CattleBreed::CostenoConCuernos => "Costeño con Cuernos".to_string(),
            CattleBreed::DutchBelted => "Dutch Belted (Lakenvelder)".to_string(),
            CattleBreed::HolandoArgentino => "Holando-Argentino".to_string(),
            CattleBreed::IndoBrazilian => "Indo-Brazilian".to_string(),
            CattleBreed::LatvianBrown => "Latvian Brown (Buraya Latviiskaya)".to_string(),
            CattleBreed::MaineAnjou => "Maine-Anjou".to_string(),
            CattleBreed::MeuseRhineYssel => "Meuse-Rhine-Yssel".to_string(),
            CattleBreed::Montbeliard => "Montbéliarde".to_string(),
            CattleBreed::Muturu => "Muturu - West African Dwarf Shorthorn".to_string(),
            CattleBreed::Ndama => "N'dama".to_string(),
            CattleBreed::RedPolledOstland => "Red Polled Østland".to_string(),
            CattleBreed::SwedishRedAndWhite => "Swedish Red-and-White".to_string(),
            _ => format!("{:?}", self),
        }
    }
}

/// Converts a string to a CattleBreed enum.
///
/// # Examples
/// ``` rust
/// use livestock_rs::cattle::CattleBreed;
/// use std::str::FromStr;
///
/// let breed = CattleBreed::from_str("angus").unwrap();
/// println!("{:?}", breed);
/// ```

impl FromStr for CattleBreed {
    type Err = std::io::Error;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().replace("-", " ").as_str() {
            "africander" => Ok(CattleBreed::Africander),
            "akaushi" => Ok(CattleBreed::Akaushi),
            "alberes" => Ok(CattleBreed::Alberes),
            "alentejana" => Ok(CattleBreed::Alentejana),
            "allmogekor" => Ok(CattleBreed::Allmogekor),
            "american breed" | "american" => Ok(CattleBreed::AmericanBreed),
            "american braford" => Ok(CattleBreed::AmericanBraford),
            "american whitepark" | "american white park" => Ok(CattleBreed::AmericanWhitePark),
            "amerifax" => Ok(CattleBreed::Amerifax),
            "amrit mahal" => Ok(CattleBreed::AmritMahal),
            "anatolian black" => Ok(CattleBreed::AnatolianBlack),
            "andalusian black" => Ok(CattleBreed::AndalusianBlack),
            "andalusian grey" => Ok(CattleBreed::AndalusianGrey),
            "angeln" => Ok(CattleBreed::Angeln),
            "angus" => Ok(CattleBreed::Angus),
            "ankole" => Ok(CattleBreed::Ankole),
            "ankole watusi" => Ok(CattleBreed::AnkoleWatusi),
            "argentine criollo" => Ok(CattleBreed::ArgentineCriollo),
            "asturian mountain" => Ok(CattleBreed::AsturianMountain),
            "asturian valley" => Ok(CattleBreed::AsturianValley),
            "aubrac" => Ok(CattleBreed::Aubrac),
            "aulie ata" => Ok(CattleBreed::AulieAta),
            "australian braford" => Ok(CattleBreed::AustralianBraford),
            "australian friesian sahiwal" => Ok(CattleBreed::AustralianFriesianSahiwal),
            "australian lowline" => Ok(CattleBreed::AustralianLowline),
            "australian milking zebu" => Ok(CattleBreed::AustralianMilkingZebu),
            "ayrshire" => Ok(CattleBreed::Ayrshire),
            "azaouak" => Ok(CattleBreed::Azaouak),
            "bachaur" => Ok(CattleBreed::Bachaur),
            "baladi" => Ok(CattleBreed::Baladi),
            "baltata romaneasca" => Ok(CattleBreed::BaltataRomaneasca),
            "barka" => Ok(CattleBreed::Barka),
            "barzona" => Ok(CattleBreed::Barzona),
            "bazadais" => Ok(CattleBreed::Bazadais),
            "bearnais" | "béarnais" => Ok(CattleBreed::Bearnais),
            "beefalo" => Ok(CattleBreed::Beefalo),
            "beefmaker" => Ok(CattleBreed::Beefmaker),
            "beefmaster" => Ok(CattleBreed::Beefmaster),
            "belarus red" => Ok(CattleBreed::BelarusRed),
            "belgian blue" => Ok(CattleBreed::BelgianBlue),
            "belgian red" => Ok(CattleBreed::BelgianRed),
            "belmont adaptaur" => Ok(CattleBreed::BelmontAdaptaur),
            "belmont red" => Ok(CattleBreed::BelmontRed),
            "belted galloway" => Ok(CattleBreed::BeltedGalloway),
            "bengali" => Ok(CattleBreed::Bengali),
            "berrendas" => Ok(CattleBreed::Berrendas),
            "bhagnari" => Ok(CattleBreed::Bhagnari),
            "black hereford" => Ok(CattleBreed::BlackHereford),
            "blacksided trondheim and norland" => Ok(CattleBreed::BlacksidedTrondheimAndNorland),
            "blanca cacerena" | "blanca cacereña" | "white cáceres" | "white caceres" | "blanca cacerena/white caceres" | "blanca cacereña/white cáceres" | "blanca cacerena/white cáceres" | "blanca cacereña/white caceres" => Ok(CattleBreed::BlancaCacerena),
            "blanco orejinegro" => Ok(CattleBreed::BlancoOrejinegro),
            "blonde d'aquitaine" => Ok(CattleBreed::BlondeDAquitaine),
            "bonsmara" => Ok(CattleBreed::Bonsmara),
            "boran" => Ok(CattleBreed::Boran),
            "bordelais" => Ok(CattleBreed::Bordelais),
            "brahman" => Ok(CattleBreed::Brahman),
            "brahmousin" => Ok(CattleBreed::Brahmousin),
            "brangus" => Ok(CattleBreed::Brangus),
            "braunvieh" => Ok(CattleBreed::Braunvieh),
            "british white" => Ok(CattleBreed::BritishWhite),
            "brown swiss" => Ok(CattleBreed::BrownSwiss),
            "busa" => Ok(CattleBreed::Busa),
            "cachena" => Ok(CattleBreed::Cachena),
            "canadian highland" => Ok(CattleBreed::CanadianHighland),
            "canadienne" => Ok(CattleBreed::Canadienne),
            "canary island" => Ok(CattleBreed::CanaryIsland),
            "canchim" => Ok(CattleBreed::Canchim),
            "carinthian blond" => Ok(CattleBreed::CarinthianBlond),
            "caucasian" => Ok(CattleBreed::Caucasian),
            "channi" => Ok(CattleBreed::Channi),
            "charbray" => Ok(CattleBreed::Charbray),
            "charolais" => Ok(CattleBreed::Charolais),
            "chianina" => Ok(CattleBreed::Chianina),
            "chinampo" => Ok(CattleBreed::Chinampo),
            "chinese black and white" => Ok(CattleBreed::ChineseBlackAndWhite),
            "chinese mongolian" => Ok(CattleBreed::ChineseMongolian),
            "chinese xinjiang brown" => Ok(CattleBreed::ChineseXinjiangBrown),
            "cholistani" => Ok(CattleBreed::Cholistani),
            "corriente" => Ok(CattleBreed::Corriente),
            "costeno con cuernos" | "costeño con cuernos" => Ok(CattleBreed::CostenoConCuernos),
            "dajal" => Ok(CattleBreed::Dajal),
            "damascus" => Ok(CattleBreed::Damascus),
            "damietta" => Ok(CattleBreed::Damietta),
            "dangi" => Ok(CattleBreed::Dangi),
            "danish jersey" => Ok(CattleBreed::DanishJersey),
            "danish red" => Ok(CattleBreed::DanishRed),
            "deoni" => Ok(CattleBreed::Deoni),
            "devon" => Ok(CattleBreed::Devon),
            "dexter" => Ok(CattleBreed::Dexter),
            "dhanni" => Ok(CattleBreed::Dhanni),
            "djali" => Ok(CattleBreed::Djali),
            "dolafe" | "dølafe" => Ok(CattleBreed::Dolafe),
            "droughtmaster" => Ok(CattleBreed::Droughtmaster),
            "dulong" => Ok(CattleBreed::Dulong),
            "dutch belted" | "lakenvelder" | "dutch belted (lakenvelder)" | "dutch belted/lakenvelder" | "lakenvelder/dutch belted" => Ok(CattleBreed::DutchBelted),
            "dutch friesian" => Ok(CattleBreed::DutchFriesian),
            "east anatolian red" => Ok(CattleBreed::EastAnatolianRed),
            "enderby island" => Ok(CattleBreed::EnderbyIsland),
            "english longhorn" => Ok(CattleBreed::EnglishLonghorn),
            "estonian red" => Ok(CattleBreed::EstonianRed),
            "evolene" | "evolène" => Ok(CattleBreed::Evolene),
            "fighting" => Ok(CattleBreed::Fighting),
            "finnish" => Ok(CattleBreed::Finnish),
            "fjall" => Ok(CattleBreed::Fjall),
            "florida cracker" => Ok(CattleBreed::FloridaCracker),
            "galician blond" => Ok(CattleBreed::GalicianBlond),
            "galloway" => Ok(CattleBreed::Galloway),
            "gaolao" => Ok(CattleBreed::Gaolao),
            "gascon" => Ok(CattleBreed::Gascon),
            "gelbray" => Ok(CattleBreed::Gelbray),
            "gelbvieh" => Ok(CattleBreed::Gelbvieh),
            "german angus moiled" => Ok(CattleBreed::GermanAngusMoiled),
            "german red pied" => Ok(CattleBreed::GermanRedPied),
            "gir" => Ok(CattleBreed::Gir),
            "glan" => Ok(CattleBreed::Glan),
            "gloucester" => Ok(CattleBreed::Gloucester),
            "gobra" => Ok(CattleBreed::Gobra),
            "greek shorthorn" => Ok(CattleBreed::GreekShorthorn),
            "greek steppe" => Ok(CattleBreed::GreekSteppe),
            "groningen" => Ok(CattleBreed::Groningen),
            "guernsey" => Ok(CattleBreed::Guernsey),
            "guzerat" => Ok(CattleBreed::Guzerat),
            "hallikar" => Ok(CattleBreed::Hallikar),
            "hariana" => Ok(CattleBreed::Hariana),
            "harton" => Ok(CattleBreed::Harton),
            "hays converter" => Ok(CattleBreed::HaysConverter),
            "hereford" => Ok(CattleBreed::Hereford),
            "herens" => Ok(CattleBreed::Herens),
            "highland" => Ok(CattleBreed::Highland),
            "hinterwald" => Ok(CattleBreed::Hinterwald),
            "holando argentino" => Ok(CattleBreed::HolandoArgentino),
            "holstein" => Ok(CattleBreed::Holstein),
            "horro" => Ok(CattleBreed::Horro),
            "hungarian grey" => Ok(CattleBreed::HungarianGrey),
            "icelandic" => Ok(CattleBreed::Icelandic),
            "illawarra" => Ok(CattleBreed::Illawarra),
            "indo brazilian" => Ok(CattleBreed::IndoBrazilian),
            "irish moiled" => Ok(CattleBreed::IrishMoiled),
            "israeli holstein" => Ok(CattleBreed::IsraeliHolstein),
            "israeli red" => Ok(CattleBreed::IsraeliRed),
            "istoben" => Ok(CattleBreed::Istoben),
            "jamaica black" => Ok(CattleBreed::JamaicaBlack),
            "jamaica hope" => Ok(CattleBreed::JamaicaHope),
            "jamaica red" => Ok(CattleBreed::JamaicaRed),
            "jaulan" => Ok(CattleBreed::Jaulan),
            "jaulan sharabi" | "sharabi" => Ok(CattleBreed::JaulanSharabi),
            "jersey" => Ok(CattleBreed::Jersey),
            "kangayam" => Ok(CattleBreed::Kangayam),
            "kankrej" => Ok(CattleBreed::Kankrej),
            "karan fries" => Ok(CattleBreed::KaranFries),
            "karan swiss" => Ok(CattleBreed::KaranSwiss),
            "kazakh" => Ok(CattleBreed::Kazakh),
            "kenwariya" => Ok(CattleBreed::Kenwariya),
            "kerry" => Ok(CattleBreed::Kerry),
            "kherigarh" => Ok(CattleBreed::Kherigarh),
            "khillari" => Ok(CattleBreed::Khillari),
            "kholmogory" => Ok(CattleBreed::Kholmogory),
            "kilis" => Ok(CattleBreed::Kilis),
            "krishna valley" => Ok(CattleBreed::KrishnaValley),
            "kurdi black" => Ok(CattleBreed::KurdiBlack),
            "kuri" => Ok(CattleBreed::Kuri),
            "latvian brown" | "buraya latviiskaya" | "latvian brown (buraya latviiskaya)" => Ok(CattleBreed::LatvianBrown),
            "limousin" => Ok(CattleBreed::Limousin),
            "limpurger" => Ok(CattleBreed::Limpurger),
            "lincoln red" => Ok(CattleBreed::LincolnRed),
            "lithuanian red" => Ok(CattleBreed::LithuanianRed),
            "lohani" => Ok(CattleBreed::Lohani),
            "lourdais" => Ok(CattleBreed::Lourdais),
            "luing" => Ok(CattleBreed::Luing),
            "madagascar zebu" => Ok(CattleBreed::MadagascarZebu),
            "maine anjou" => Ok(CattleBreed::MaineAnjou),
            "malvi" => Ok(CattleBreed::Malvi),
            "mandalong" => Ok(CattleBreed::Mandalong),
            "marchigiana" => Ok(CattleBreed::Marchigiana),
            "maremmana" => Ok(CattleBreed::Maremmana),
            "masai" => Ok(CattleBreed::Masai),
            "mashona" => Ok(CattleBreed::Mashona),
            "maure" => Ok(CattleBreed::Maure),
            "mazandarani" => Ok(CattleBreed::Mazandarani),
            "meuse rhine yssel" => Ok(CattleBreed::MeuseRhineYssel),
            "mewati" => Ok(CattleBreed::Mewati),
            "milking devon" => Ok(CattleBreed::MilkingDevon),
            "milking shorthorn" => Ok(CattleBreed::MilkingShorthorn),
            "miniature zebu" => Ok(CattleBreed::MiniatureZebu),
            "mirandesa" => Ok(CattleBreed::Mirandesa),
            "modicana" => Ok(CattleBreed::Modicana),
            "montbeliard" | "montbéliard" => Ok(CattleBreed::Montbeliard),
            "morucha" => Ok(CattleBreed::Morucha),
            "murboden" => Ok(CattleBreed::Murboden),
            "murray grey" => Ok(CattleBreed::MurrayGrey),
            "muturu" | "west african dwarf shorthorn" | "muturu   west african dwarf shorthorn" => Ok(CattleBreed::Muturu),
            "ndama" | "n'dama" => Ok(CattleBreed::Ndama),
            "nagori" => Ok(CattleBreed::Nagori),
            "nanyang" => Ok(CattleBreed::Nanyang),
            "nelore" => Ok(CattleBreed::Nelore),
            "nguni" => Ok(CattleBreed::Nguni),
            "nimari" => Ok(CattleBreed::Nimari),
            "normande" => Ok(CattleBreed::Normande),
            "norwegian red" => Ok(CattleBreed::NorwegianRed),
            "ongole" => Ok(CattleBreed::Ongole),
            "orma boran" => Ok(CattleBreed::OrmaBoran),
            "oropa" => Ok(CattleBreed::Oropa),
            "ovambo" => Ok(CattleBreed::Ovambo),
            "parthenais" => Ok(CattleBreed::Parthenais),
            "philippine native" => Ok(CattleBreed::PhilippineNative),
            "piedmontese" => Ok(CattleBreed::Piedmontese),
            "pinzgauer" => Ok(CattleBreed::Pinzgauer),
            "polish red" => Ok(CattleBreed::PolishRed),
            "polled hereford" => Ok(CattleBreed::PolledHereford),
            "ponwar" => Ok(CattleBreed::Ponwar),
            "qinchuan" => Ok(CattleBreed::Qinchuan),
            "rath" => Ok(CattleBreed::Rath),
            "rathi" => Ok(CattleBreed::Rathi),
            "ratien gray" | "rätien gray" => Ok(CattleBreed::RatienGray),
            "red angus" => Ok(CattleBreed::RedAngus),
            "red brangus" => Ok(CattleBreed::RedBrangus),
            "red fulani" => Ok(CattleBreed::RedFulani),
            "red pied friesian" => Ok(CattleBreed::RedPiedFriesian),
            "red poll" => Ok(CattleBreed::RedPoll),
            "red polled ostland" | "red polled østland" => Ok(CattleBreed::RedPolledOstland),
            "red sindhi" => Ok(CattleBreed::RedSindhi),
            "red steppe" => Ok(CattleBreed::RedSteppe),
            "reggiana" => Ok(CattleBreed::Reggiana),
            "retinta" => Ok(CattleBreed::Retinta),
            "rojhan" => Ok(CattleBreed::Rojhan),
            "romagnola" => Ok(CattleBreed::Romagnola),
            "romosinuano" => Ok(CattleBreed::Romosinuano),
            "russian black pied" => Ok(CattleBreed::RussianBlackPied),
            "rx3" => Ok(CattleBreed::RX3),
            "sahiwal" => Ok(CattleBreed::Sahiwal),
            "salers" => Ok(CattleBreed::Salers),
            "salorn" => Ok(CattleBreed::Salorn),
            "san martinero" => Ok(CattleBreed::SanMartinero),
            "sanhe" => Ok(CattleBreed::Sanhe),
            "santa cruz" => Ok(CattleBreed::SantaCruz),
            "santa gertrudis" => Ok(CattleBreed::SantaGertrudis),
            "sarabi" => Ok(CattleBreed::Sarabi),
            "senepol" => Ok(CattleBreed::Senepol),
            "shetland" => Ok(CattleBreed::Shetland),
            "shorthorn" => Ok(CattleBreed::Shorthorn),
            "siboney" => Ok(CattleBreed::Siboney),
            "simbra" | "simbrah" => Ok(CattleBreed::Simbrah),
            "simmental" => Ok(CattleBreed::Simmental),
            "siri" => Ok(CattleBreed::Siri),
            "slovenian cika" => Ok(CattleBreed::SlovenianCika),
            "south devon" => Ok(CattleBreed::SouthDevon),
            "sudanese fulani" => Ok(CattleBreed::SudaneseFulani),
            "sussex" => Ok(CattleBreed::Sussex),
            "swedish friesian" => Ok(CattleBreed::SwedishFriesian),
            "swedish red polled" => Ok(CattleBreed::SwedishRedPolled),
            "swedish red and white" => Ok(CattleBreed::SwedishRedAndWhite),
            "tarentaise" => Ok(CattleBreed::Tarentaise),
            "telemark" => Ok(CattleBreed::Telemark),
            "texas longhorn" => Ok(CattleBreed::TexasLonghorn),
            "texon" => Ok(CattleBreed::Texon),
            "tharparkar" => Ok(CattleBreed::Tharparkar),
            "tswana" => Ok(CattleBreed::Tswana),
            "tuli" => Ok(CattleBreed::Tuli),
            "turkish grey steppe" => Ok(CattleBreed::TurkishGreySteppe),
            "ukrainian beef" => Ok(CattleBreed::UkrainianBeef),
            "ukrainian grey" => Ok(CattleBreed::UkrainianGrey),
            "ukrainian whitehead" => Ok(CattleBreed::UkrainianWhitehead),
            "umblachery" => Ok(CattleBreed::Umblachery),
            "ural black pied" => Ok(CattleBreed::UralBlackPied),
            "vestland fjord" => Ok(CattleBreed::VestlandFjord),
            "vestland red polled" => Ok(CattleBreed::VestlandRedPolled),
            "vosges" => Ok(CattleBreed::Vosges),
            "wagyu" => Ok(CattleBreed::Wagyu),
            "welsh black" => Ok(CattleBreed::WelshBlack),
            "white park" => Ok(CattleBreed::WhitePark),
            "yanbian" => Ok(CattleBreed::Yanbian),
            _ => Err(std::io::Error::new(std::io::ErrorKind::InvalidInput, "Invalid cattle breed")),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_to_string_special_cases() {
        let breeds = [
            (CattleBreed::AnkoleWatusi, "Ankole-Watusi"),
            (CattleBreed::AulieAta, "Aulie-Ata"),
            (CattleBreed::Bearnais, "Béarnais"),
            (CattleBreed::BlancaCacerena, "Blanca Cacereña/White Cáceres"),
            (CattleBreed::BlondeDAquitaine, "Blonde d'Aquitaine"),
            (CattleBreed::ChineseBlackAndWhite, "Chinese Black-and-White"),
            (CattleBreed::CostenoConCuernos, "Costeño con Cuernos"),
            (CattleBreed::DutchBelted, "Dutch Belted (Lakenvelder)"),
            (CattleBreed::HolandoArgentino, "Holando-Argentino"),
            (CattleBreed::IndoBrazilian, "Indo-Brazilian"),
            (CattleBreed::LatvianBrown, "Latvian Brown (Buraya Latviiskaya)"),
            (CattleBreed::MaineAnjou, "Maine-Anjou"),
            (CattleBreed::MeuseRhineYssel, "Meuse-Rhine-Yssel"),
            (CattleBreed::Montbeliard, "Montbéliarde"),
            (CattleBreed::Muturu, "Muturu - West African Dwarf Shorthorn"),
            (CattleBreed::Ndama, "N'dama"),
            (CattleBreed::RedPolledOstland, "Red Polled Østland"),
            (CattleBreed::SwedishRedAndWhite, "Swedish Red-and-White"),
        ];

        for (breed, expected) in breeds.iter() {
            assert_eq!(breed.to_string(), *expected);
        }
    }

    #[test]
    fn test_from_str_special_cases() {
        let breeds = [
            ("Ankole-Watusi", CattleBreed::AnkoleWatusi),
            ("Aulie-Ata", CattleBreed::AulieAta),
            ("Béarnais", CattleBreed::Bearnais),
            ("Blanca Cacereña/White Cáceres", CattleBreed::BlancaCacerena),
            ("Blonde d'Aquitaine", CattleBreed::BlondeDAquitaine),
            ("Chinese Black-and-White", CattleBreed::ChineseBlackAndWhite),
            ("Costeño con Cuernos", CattleBreed::CostenoConCuernos),
            ("Dutch Belted (Lakenvelder)", CattleBreed::DutchBelted),
            ("Holando-Argentino", CattleBreed::HolandoArgentino),
            ("Indo-Brazilian", CattleBreed::IndoBrazilian),
            ("Latvian Brown (Buraya Latviiskaya)", CattleBreed::LatvianBrown),
            ("Maine-Anjou", CattleBreed::MaineAnjou),
            ("Meuse-Rhine-Yssel", CattleBreed::MeuseRhineYssel),
            ("Montbéliard", CattleBreed::Montbeliard),
            ("Muturu - West African Dwarf Shorthorn", CattleBreed::Muturu),
            ("N'dama", CattleBreed::Ndama),
            ("Red Polled Østland", CattleBreed::RedPolledOstland),
            ("Swedish Red-and-White", CattleBreed::SwedishRedAndWhite),
        ];

        for (breed, expected) in breeds.iter() {
            assert_eq!(CattleBreed::from_str(*breed).unwrap(), *expected);
        }
    }
}
