name: Rust CI and Publish

on:
  pull_request:
    branches:
      - main
      - master
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
  push:
    branches:
      - main  # Trigger on push to main branch
    paths:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    - name: Install dependencies and run tests
      run: |
        cargo check
        cargo test

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Only run on push to `main`

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    - name: Publish to crates.io
      run: |
        cargo login ${{ secrets.CARGO_TOKEN }}  # Login to crates.io
        cargo publish --no-verify  # Publish the crate